Total Aprovado =
SUM ( BaseProducao[Qtd Aprovada] )

Total Rejeitado =
SUM ( BaseProducao[Qtd Rejeitada] )

Horas Totais =
SUM ( BaseProducao[Total Horas] )

Horas Produtivas =
CALCULATE (
    [Horas Totais],
    BaseProducao[Tipo Hora] = "Produtiva"
)

Horas Paradas =
CALCULATE (
    [Horas Totais],
    BaseProducao[Tipo Hora] = "Parada"
)

Disponibilidade =
DIVIDE ( [Horas Produtivas], [Horas Totais] )

Qualidade =
DIVIDE ( [Total Aprovado], [Total Aprovado] + [Total Rejeitado] )

Aprovado Mil =
DIVIDE ( [Total Aprovado], 1000 )

Mes Ordenacao =
MIN ( BaseProducao[Mes Numero] )
